# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: 设置go版本
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: 更新go依赖
      run:  cd Back && pwd && go mod download
    - name: 编译go程序
      run:  cd Back && pwd && go build -o nas_go ./src/main.go
    - name: 上传执行文件
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "./Back/nas_go"
        target: "/usr/nas_exe"
    - name: 部署
      uses: appleboy/ssh-action@v1.2.0
      with:
        debug: true
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script:
          nohup /usr/nas_exe/Back/nas_go > /dev/null 2>&1 &

      


